export const SET_BOARDS = "SET_BOARDS";
export const SEARCH_BOARD = "SEARCH_BOARD";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER = "REGISTER";

export const FETCH_TASKS = "FETCH_TASKS";
export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_COMPLETION_STATUS = " TOGGLE_COMPLETION_STATUS";
export const UPDATE_TASK_DUE_DATE = "UPDATE_TASK_DUE_DATE";