export const CREATE_BOARD = "CREATE_BOARD"
export const SET_BOARDS = "SET_BOARDS";
export const SEARCH_BOARD = "SEARCH_BOARD";
export const JOIN_BOARD = "JOIN_BOARD";
export const ACCEPT_JOIN = "ACCEPT_JOIN";
export const REJECT_JOIN = "REJECT_JOIN";
export const FETCH_JOIN_REQUESTS = "FETCH_JOIN_REQUESTS";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_TASKS = "FETCH_TASKS";
export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_COMPLETION_STATUS = " TOGGLE_COMPLETION_STATUS";
export const UPDATE_TASK_DUE_DATE = "UPDATE_TASK_DUE_DATE";
export const ADD_TAG_TO_TASK = "ADD_TAG_TO_TASK";
export const DELETE_TAG = "DELETE_TAG";